# Generated by Django 4.1.7 on 2023-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
